### ISSUE TITLE
Add AWS credentials to GitHub Secrets

### ISSUE THREAD

**Issue by pjsier** [pgh-public-meetings/city-scrapers-pitt#100]
For the GitHub Actions cron task to run you'll need to add the AWS credentials to the repo's secrets. More info on that here https://help.github.com/en/actions/configuring-and-managing-workflows/creating-and-storing-encrypted-secrets

**Comment by pjsier** [comment]
@bonfirefan based on the scraper results it looks like this still isn't set? Happy to help clarify anything here!

**Comment by bonfirefan** [comment]
Hmm this was added 2 weeks ago! 
The error then was 
```
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (AuthorizationHeaderMalformed) when calling the ListObjects operation: The authorization header is malformed; a non-empty Access Key (AKID) must be provided in the credential.
##[error]Process completed with exit code 1.
```
Now the error is 
```
Run export PYTHONPATH=$(pwd):$PYTHONPATH
Traceback (most recent call last):
  File "/home/runner/work/city-scrapers-pitt/city-scrapers-pitt/.venv/lib/python3.7/site-packages/botocore/httpsession.py", line 263, in send
    chunked=self._chunked(request.headers),
  File "/home/runner/work/city-scrapers-pitt/city-scrapers-pitt/.venv/lib/python3.7/site-packages/urllib3/connectionpool.py", line 672, in urlopen
    chunked=chunked,
  File "/home/runner/work/city-scrapers-pitt/city-scrapers-pitt/.venv/lib/python3.7/site-packages/urllib3/connectionpool.py", line 387, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/opt/hostedtoolcache/Python/3.7.6/x64/lib/python3.7/http/client.py", line 1252, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/home/runner/work/city-scrapers-pitt/city-scrapers-pitt/.venv/lib/python3.7/site-packages/botocore/awsrequest.py", line 92, in _send_request
    method, url, body, headers, *args, **kwargs)
  File "/opt/hostedtoolcache/Python/3.7.6/x64/lib/python3.7/http/client.py", line 1293, in _send_request
    self.putheader(hdr, value)
  File "/opt/hostedtoolcache/Python/3.7.6/x64/lib/python3.7/http/client.py", line 1230, in putheader
    raise ValueError('Invalid header value %r' % (values[i],))
ValueError: Invalid header value b'AWS4-HMAC-SHA256 Credential=***\n/20200306/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=e9733c00fe34cbcdad02f2c776d2483299f03e7f9292c9850d34922fc0db4f7f'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/work/city-scrapers-pitt/city-scrapers-pitt/.venv/bin/scrapy", line 8, in <module>
    sys.exit(execute())
```
```

**Comment by bonfirefan** [comment]
It could be I added the wrong secrets?
We have the following:
`AWS_ACCESS_KEY_ID`
`AWS_SECRET_ACCESS_KEY`
`SENTRY_DSN`

**Comment by pjsier** [comment]
Hmm, maybe try updating the dependencies? Might have something to do with an older version of `city-scrapers-core` and its `boto3` dependency

**Comment by bonfirefan** [comment]
This has been resolved - the secret was `AWS_ACCESS_KEY `
