### ISSUE TITLE
Cron fail: boto3

### ISSUE THREAD

**Issue by bonfirefan** [pgh-public-meetings/city-scrapers-pitt#163]
Github Action CRON issue: 
https://github.com/pgh-public-meetings/city-scrapers-pitt/actions/runs/238978404

```
Run export PYTHONPATH=$(pwd):$PYTHONPATH
Traceback (most recent call last):
  File "/home/runner/work/city-scrapers-pitt/city-scrapers-pitt/.venv/bin/scrapy", line 8, in <module>
    sys.exit(execute())
  File "/home/runner/work/city-scrapers-pitt/city-scrapers-pitt/.venv/lib/python3.7/site-packages/scrapy/cmdline.py", line 143, in execute
    _run_print_help(parser, _run_command, cmd, args, opts)
  File "/home/runner/work/city-scrapers-pitt/city-scrapers-pitt/.venv/lib/python3.7/site-packages/scrapy/cmdline.py", line 98, in _run_print_help
    func(*a, **kw)
  File "/home/runner/work/city-scrapers-pitt/city-scrapers-pitt/.venv/lib/python3.7/site-packages/scrapy/cmdline.py", line 151, in _run_command
    cmd.run(args, opts)
  File "/home/runner/work/city-scrapers-pitt/city-scrapers-pitt/.venv/lib/python3.7/site-packages/city_scrapers_core/commands/combinefeeds.py", line 22, in run
    self.combine_s3()
  File "/home/runner/work/city-scrapers-pitt/city-scrapers-pitt/.venv/lib/python3.7/site-packages/city_scrapers_core/commands/combinefeeds.py", line 31, in combine_s3
    import boto3
ModuleNotFoundError: No module named 'boto3'
##[error]Process completed with exit code 1.
```

**Comment by bonfirefan** [comment]
uninstall city-scraper-core and re-install city-scrapers-core[aws]
`pipenv uninstall city-scrapers-core`
`pipenv install city-scrapers-core[aws]`

this will re-generate the pipfile lock file to get rid of the azure extras, replace aws and install boto3

**Comment by will-snavely** [comment]
This appears to be addressed by https://github.com/pgh-public-meetings/city-scrapers-pitt/pull/162

**Comment by ben-nathanson** [comment]
I agree with the previous comment. In addition, the most recent [cron job](https://github.com/pgh-public-meetings/city-scrapers-pitt/actions/runs/240435875) after the change was successful.
